import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('https://www.blue-style.cz/');

    await page.pause();
    // await page.waitForTimeout(2000);
    await page.locator('[id="wrapper\\.depCity"] div').nth(1).click();
    await page.waitForTimeout(1500);
    await page.getByRole('button', { name: 'Accept all' }).click();
    await page.waitForTimeout(1000);
    await page.locator('[id="wrapper\\.depCity"] span').nth(3).click();
    await page.getByRole('button', { name: 'Praha' }).click();
    await page.waitForTimeout(2000);
    // await page.locator('iframe[title="Zde najdete více informací"]').contentFrame().getByRole('button', { name: 'Minimalizovat widget' }).click();
    await page.waitForTimeout(2000);
    await page.getByRole('button', { name: 'Místo příletu' }).click();
    await page.waitForTimeout(2000);
    await page.getByRole('button', { name: 'Egypt Toggle' }).click();
    await page.waitForTimeout(2000);
    await page.getByRole('button', { name: 'Vybrat' }).click();
    await page.waitForTimeout(2000);
    await page.getByText('Termín odletu').click();
    await page.getByLabel('Wed May 14').getByText('14Termín odletu').click();
    await page.getByLabel('Sun Jun 15').getByText('15Termín návratu').click();
    await page.waitForTimeout(2000);
    await page.getByRole('button', { name: 'Vybrat a zavřít' }).click();
    await page.getByRole('button', { name: 'Zobrazit zájezdy' }).click();
    await page.waitForTimeout(2000);
    await page.locator('.hideOnDesktop > .hotelCard__btn > .btn').first().click();
    await page.getByRole('button', { name: 'Rezervovat' }).click();
    await page.waitForTimeout(2000);
    await page.locator('[id="customer\\.firstName"]').click();
    await page.locator('[id="customer\\.firstName"]').fill('test');
    await page.locator('[id="customer\\.lastName"]').click();
    await page.locator('[id="customer\\.lastName"]').fill('user');
    await page.getByRole('textbox', { name: 'E-mail' }).click();
    await page.waitForTimeout(2000);
    await page.getByRole('textbox', { name: 'E-mail' }).fill('testusera@gmail.com');
    await page.locator('input[name="customer\\.birthDate"]').click();
    await page.locator('input[name="customer\\.birthDate"]').fill('02.03.2001');
    await page.getByRole('textbox', { name: 'Ulice' }).click();
    await page.waitForTimeout(2000);
    await page.getByRole('textbox', { name: 'Ulice' }).fill('test');
    await page.getByRole('textbox', { name: 'Číslo popisné' }).click();
    await page.getByRole('textbox', { name: 'Číslo popisné' }).fill('31');
    await page.getByRole('textbox', { name: 'Telefonní číslo' }).click();
    await page.getByRole('textbox', { name: 'Telefonní číslo' }).fill('+420 235 456 230');
    await page.locator('[id="wrapper\\.customer\\.address\\.city"]').click();
    await page.getByRole('textbox', { name: 'Město' }).fill('test');
    await page.getByRole('textbox', { name: 'PSČ' }).click();
    await page.getByRole('textbox', { name: 'PSČ' }).fill('k');
    await page.getByRole('textbox', { name: 'PSČ' }).click();
    await page.getByRole('textbox', { name: 'PSČ' }).fill('l');
    await page.locator('[id="wrapper\\.passengers\\[0\\]\\.title"] span').nth(2).click();
    await page.getByRole('button', { name: 'Pan', exact: true }).click();
    await page.getByText('Vyberte').click();
    await page.getByRole('button', { name: 'Paní' }).click();
    await page.locator('[id="passengers\\[1\\]\\.firstName"]').click();
    await page.locator('[id="passengers\\[1\\]\\.firstName"]').fill('test');
    await page.locator('[id="passengers\\[1\\]\\.firstName"]').press('Tab');
    await page.locator('[id="passengers\\[1\\]\\.lastName"]').fill('useri');
    await page.locator('input[name="passengers\\[1\\]\\.birthDate"]').click();
    await page.locator('input[name="passengers\\[1\\]\\.birthDate"]').fill('03.05.2003');
    await page.getByRole('table').filter({ hasText: '199920002001200220032004200520062007200820092010' }).click();
    await page.getByText('CestujícíPokoj 1 (Standardní').click();
    await page.getByRole('button', { name: 'Pokračovat' }).click();
    await page.getByRole('textbox', { name: 'PSČ' }).click();
    await page.getByRole('textbox', { name: 'PSČ' }).fill('343 334');
    await page.getByRole('button', { name: 'Pokračovat' }).click();
    await page.locator('label').filter({ hasText: 'Souhlasím s Všeobecnými' }).click();
    await page.locator('label').filter({ hasText: 'Četl/a jsem a souhlasím se zá' }).locator('div').click();
    await page.getByRole('button', { name: 'Pokračovat' }).click();
    await page.locator('label').filter({ hasText: 'Seznámil/a jsem se a souhlasí' }).locator('div').click();
});