import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.blue-style.cz/');
   await page.pause();
  await page.getByRole('button', { name: 'Accept all' }).click();
  await page.getByRole('option', { name: 'Místo odletu' }).click();
  await page.getByRole('button', { name: 'Praha' }).click();
  await page.getByRole('button', { name: 'Místo příletu' }).click();
  await page.getByRole('button', { name: 'Egypt Toggle' }).click();
  await page.getByRole('button', { name: 'Vybrat' }).click();
  await page.locator('.dayPickerInput__val').click();
  await page.getByLabel('Fri May 16').getByText('16Termín odletu').click();
  await page.getByRole('button', { name: 'Vybrat a zavřít' }).click();
  await page.getByRole('button', { name: 'Zobrazit zájezdy' }).click();
  await page.locator('.hideOnDesktop > .hotelCard__btn > .btn').first().click();
  await page.goto('https://www.blue-style.cz/egypt/hurghada/hotel-pickalbatros-dana-beach-resort/?airline=Smartwings&arrCity=9&date=2025-05-16&depCity=2&duration=7&room1=2%7CSRGV%7CAI');
  await page.getByRole('button', { name: 'Rezervovat' }).click();
  await page.locator('[id="customer\\.firstName"]').click();
  await page.locator('[id="customer\\.firstName"]').fill('test');
  await page.locator('[id="customer\\.lastName"]').click();
  await page.locator('[id="customer\\.lastName"]').fill('user');
  await page.getByRole('textbox', { name: 'Telefonní číslo' }).click();
  await page.getByRole('textbox', { name: 'Telefonní číslo' }).fill('+420 765 787 654');
  await page.getByRole('textbox', { name: 'E-mail' }).click();
  await page.getByRole('textbox', { name: 'E-mail' }).fill('testuserw@gmail.com');
  await page.locator('input[name="customer\\.birthDate"]').click();
  await page.locator('input[name="customer\\.birthDate"]').fill('02.03.2003');
  await page.getByRole('textbox', { name: 'Ulice' }).click();
  await page.getByRole('textbox', { name: 'Ulice' }).fill('test');
  await page.getByRole('textbox', { name: 'Číslo popisné' }).click();
  await page.getByRole('textbox', { name: 'Číslo popisné' }).fill('yheunb');
  await page.getByRole('textbox', { name: 'Město' }).click();
  await page.getByRole('textbox', { name: 'Město' }).fill('test');
  await page.getByRole('textbox', { name: 'PSČ' }).click();
  await page.getByRole('textbox', { name: 'PSČ' }).fill('343 343');
  await page.locator('[id="wrapper\\.customer\\.passportIssuePlace"] div').nth(2).click();
  await page.getByRole('button', { name: 'Česká republika' }).click();
  await page.locator('[id="wrapper\\.passengers\\[0\\]\\.title"] span').nth(2).click();
  await page.getByRole('button', { name: 'Pan', exact: true }).click();
  await page.getByRole('button', { name: 'Pokračovat' }).click();
  await page.locator('[id="wrapper\\.passengers\\[1\\]\\.title"] span').nth(1).click();
  await page.getByRole('button', { name: 'Paní' }).click();
  await page.locator('[id="passengers\\[1\\]\\.firstName"]').click();
  await page.locator('[id="passengers\\[1\\]\\.firstName"]').fill('test');
  await page.locator('[id="passengers\\[1\\]\\.lastName"]').click();
  await page.locator('[id="passengers\\[1\\]\\.lastName"]').fill('account');
  await page.locator('input[name="passengers\\[1\\]\\.birthDate"]').click();
  await page.getByRole('cell', { name: '2000', exact: true }).click();
  await page.locator('input[name="passengers\\[1\\]\\.birthDate"]').click();
  await page.locator('input[name="passengers\\[1\\]\\.birthDate"]').fill('02.01.2201');
  await page.getByText('CestujícíPokoj 1 (Standardní').click();
  await page.getByRole('button', { name: 'Pokračovat' }).click();
  await page.locator('label').filter({ hasText: 'Mám promo kód' }).locator('div').click();
  await page.getByRole('button', { name: 'Pokračovat' }).click();
  await page.locator('input[name="passengers\\[1\\]\\.birthDate"]').click();
  await page.locator('input[name="passengers\\[1\\]\\.birthDate"]').fill('02.01.2010');
  await page.getByText('CestujícíPokoj 1 (Standardní').click();
  await page.getByRole('button', { name: 'Pokračovat' }).click();
  await page.locator('label').filter({ hasText: 'Souhlasím s Všeobecnými' }).locator('div').click();
  await page.locator('label').filter({ hasText: 'Četl/a jsem a souhlasím se zá' }).locator('div').click();
  await page.getByRole('button', { name: 'Pokračovat' }).click();
});